# fly.toml app configuration file generated for patient-water-7372 on 2023-05-15T19:20:13+12:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "patient-water-7372"
primary_region = "syd"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
