# fly.toml app configuration file generated for grislygrotto on 2023-10-04T08:59:34+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "grislygrotto"
primary_region = "syd"

[build]

[[mounts]]
  source = "grislygrotto_db"
  destination = "/mnt/db"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
