# fly.toml app configuration file generated for grislygrotto on 2023-05-23T12:32:52+12:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "grislygrotto"
primary_region = "syd"

[env]
  TZ = "Pacific/Auckland"

[[mounts]]
  source = "grislygrotto_db"
  destination = "/mnt/db"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
