//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrislyGrotto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        public int ID { get; set; }
        public string Key { get; set; }
        public byte[] Data { get; set; }
    }
}
