// <auto-generated />
namespace GrislyGrotto.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Quotes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Quotes));
        
        string IMigrationMetadata.Id
        {
            get { return "201306140013258_Quotes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
