//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrator.SqlCeToSqlSvr.CE
{
    using System;
    using System.Collections.Generic;
    
    public partial class CEPost
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public System.DateTime Created { get; set; }
        public string Type { get; set; }
        public string Content { get; set; }
    }
}
