//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrator.SqlCeToSqlSvr.CE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GrislyGrottoCeEntities : DbContext
    {
        public GrislyGrottoCeEntities()
            : base("name=GrislyGrottoCeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CEAsset> CEAssets { get; set; }
        public DbSet<CEComment> CEComments { get; set; }
        public DbSet<CEPost> CEPosts { get; set; }
    }
}
