// generated by go generate and embedStatic.go; DO NOT EDIT
// 2020-06-28T13:25:42+12:00
package main

func loadStatics() {
	embeddedStatics["favicon.png"] = `iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAMAAABEpIrGAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAMAUExURQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALMw9IgAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAYdEVYdFNvZnR3YXJlAHBhaW50Lm5ldCA0LjEuNWRHWFIAAAATSURBVDhPYxgFo2AUjAKsgIEBAAQgAAFC1XO+AAAAAElFTkSuQmCC`
	embeddedStatics["site.css"] = `body {
    font-family: 'Open Sans','Helvetica Neue',Helvetica,Arial,sans-serif;
    line-height: 1.3;
    background-color: black;
    padding: 0;
    margin: 0;
}

canvas.background-animation {
    position: fixed; 
    top: 0;
    left: 0;
    z-index:-1;
}

.site-container {
    margin-top: 0;
    margin-left: auto;
    margin-right: auto;
    max-width: 1000px;
    padding: 20px;

    background-color: #1e2125;
    color: #fff;
}

@media only screen and (max-width: 1000px) {
    body {
        margin-left: 25px;
        margin-right: 25px;
    }
}

nav {
    margin-left: 5px;
}

label {
    display: block;
    font-weight: 700;
    margin-bottom: 5px;
}

a, a:visited {
    color: #9acc14;
    font-weight: 700;
    text-decoration: none;
}

button, input, select, textarea {
    font-family: inherit;
    font-size: inherit;
    line-height: inherit;
    background-color: inherit;
    color: inherit;
    padding: 6px 12px;
}

input[type=text], input[type=password], textarea {
    display: block;
    border: 1px solid #9acc14;
    border-radius: 4px;
    background-color: #292e33;
    box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
    margin-bottom: 8px;
}

input[type=text]:focus, input[type=password]:focus, textarea:focus {
    border-color:#66afe9;
    outline:0;
    box-shadow:inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgba(102,175,233,.6)
}

input[type=submit], input[type=button] {
    transition: all .3s ease;
    font-weight: 400;
    text-align: center;
    cursor: pointer;
    background-color: inherit;
    border: 1px solid #9acc14;
    border-radius: 4px;
    padding: 6px 12px;
    font-size: 14px;
    line-height: 1.6em;
    user-select: none;
}

input[type=submit]:hover, input[type=button]:hover {
    background-color: rgba(154,204,20,.1);
}

footer {
    clear: both;
    text-align: center;
}

.site-title {
    margin-top: 0;
    margin-bottom: 0;
    font-size: 2.5em;
    text-transform: uppercase;
}

.post-title {
    margin-bottom: 0;
    font-size: 1.5em;
    text-transform: uppercase;
}

.post-summary {
    font-weight: 700;
    margin-bottom: 0.5em;
}

.post-content {
    text-align: justify;
}

.prev-link {
    margin-top: 1em;
    float: left;
}

.next-link {
    margin-top: 1em;
    float: right;
}

ul.years {
    list-style: none;
    padding: 0;
}

ul.years > li {
    float: left;
    margin-bottom: 2em;
}

ul.years > li > h3 {
    margin-bottom: 0;
}

ul.months {
    list-style: none;
    padding: 0;
}

ul.months li {
    margin-right: 2em;
}

div.stories-container {
    float: right;
    max-width: 500px;
}

ul.stories {
    list-style: none;
    padding: 0;
}

ul.stories h3 {
    margin-bottom: 0;
}

div.page-form {
    min-height: 1000px;
}

div.search-result h4 {
    margin-bottom: 0;
    text-transform: uppercase;
}

div.post-controls {
    margin-top: 20px;
    margin-bottom: 20px;
}

div.post-controls form {
    display: inline;
    margin-right: 10px;
}

.comment-summary {
    font-size: 0.8em;
    margin-top: 15px;
    margin-bottom: 4px;
}

.comment-delete input {
    padding: 2px;
    font-size: 0.8em;
    margin-top: 5px;
    margin-bottom: 5px;
}

.create-comment-container {
    margin-top: 20px;
}

div.post-controls form input {
    width: 65px;
}

div.checkbox {
    margin-bottom: 6px;
}

div.checkbox input, div.checkbox label {
    display: inline;
    vertical-align: center;
}

div.editor-help {
    float: right;
    width: 80%;
}

div.post-submit {
    clear: both;
    margin-top: 20px;
    margin-bottom: 20px;
}

span.timer {
    opacity: 50%;
    margin-top: -20px;
    position: absolute;
}

.error {
    color: red;
}

.vis-colours {
    display: none;
}

.control-panel {
    position: fixed;
    top: 10px;
    right: 10px;
}

.control-panel .controls {
    position: relative;
    float: right;
    font-size: 0.6em;
    opacity: 40%;
    text-align: right;
}

.control-panel .controls input, .control-panel .controls select {
    vertical-align: middle;
    height: 2em;
    font-size: 1em;
    padding: 0 5px 0 5px;
    margin-bottom: 5px;
    margin-top: 0;
}

@media only screen and (max-width: 1000px) {
    .control-panel {
        position: relative;
        margin-left: 14px;
    }
    
    .control-panel .controls {
        color: white;
        font-size: 0.8em;
        float: none;
        text-align: left;
        opacity: 100%;
    }
    
    .control-panel .controls input, .control-panel .controls select {
        vertical-align: middle;
    }
}`
	embeddedStatics["site.js"] = `// background animation setup

// - ensure that the canvas always fills the window

function resizeCanvas() {
    let canvas = document.getElementById('animation-left');
    canvas.width = (window.innerWidth-1000)/2;
    canvas.height = window.innerHeight;
    canvas = document.getElementById('animation-right');
    canvas.width = (window.innerWidth-1000)/2;
    canvas.style.left = (window.innerWidth-1000)/2 + 1000 + "px";
    canvas.height = window.innerHeight;
};
resizeCanvas();
window.onresize = function () { resizeCanvas(); };

// - trigger the animation

function getColour(elem) {
    return window.getComputedStyle(elem, null).getPropertyValue("background-color");
}

function initAnimation(canvasId) {
    var animationCanvas = document.getElementById(canvasId);
    var animSettings = wanderingTriangles.baseSettings();
    animSettings.backgroundColour = getColour(document.getElementById('vis-background-colour'));
    animSettings.primaryColour = getColour(document.getElementById('vis-primary-colour'));
    animSettings.secondaryColour = getColour(document.getElementById('vis-secondary-colour'));
    return wanderingTriangles.init(animationCanvas, animSettings);
}

var animationLeft = initAnimation('animation-left');
var animationRight = initAnimation('animation-right');

// visualisation control panel

document.getElementById('vis-enabled').onchange = function() {
    animationLeft.enabled = this.checked;
    animationRight.enabled = this.checked;
}
document.getElementById('site-theme').onchange = function() {
    document.getElementById('current-theme').value = this.value;
}
document.getElementById('site-theme').value = document.getElementById('current-theme').value;

// Confirm elements, e.g. deleting a comment

confirmElems = document.getElementsByClassName("confirm-click");
for (var i = 0; i < confirmElems.length; i++) {
    confirmElems[i].addEventListener("click", function () {
        return confirm("Are you sure? This action is irreversible!");
    });
}

// Dirty flag and confirm leave on editor page, to stop 'accidents'

let title = document.getElementById('title');
let content = document.getElementById('content');
if (title && content) { // both these being present means the user is on the editor page
    let dirty = false
    title.onchange = function () { dirty = true; }
    content.onchange = function () { dirty = true; }
    document.getElementById('submit').onclick = function () {
        dirty = false;
    }
    window.onbeforeunload = function () {
        if (dirty) {
            // note: most browsers ignore this and just detect that I return anything at all
            // if I do (e.g. the below 'confirm' object), then they present their own version of the below
            // I could return 1 here, or true, or even false, and it would trigger a prompt
            return confirm('are you sure you want to leave?')
        }
        // by returning nothing here, there is no prompt. note that returning false here WOULD trigger a prompt
    }
}

// cookie expiry countdown

if (title && content) {

    function updateTimer(timeRemaining) {
        minutes = Math.floor(timeRemaining / 60);
        labelClass = "timer";
        if (minutes < 10) {
            labelClass += " error";
        }
        seconds = Math.floor(timeRemaining % 60);

        let timer = document.getElementById('timer');
        if (!timer) {
            timer = document.createElement('span');
            timer.id = 'timer';
            document.querySelector('h2').insertAdjacentElement('afterend', timer);
        }
        if (minutes > 0) {
            plural = minutes == 1 ? "" : "s";
            timer.innerText = minutes+" minute"+plural+" remaining";
        } else {
            plural = seconds == 1 ? "" : "s";
            timer.innerText = seconds+" second"+plural+" remaining";
        }
        timer.className = labelClass;
    }

    start = new Date().getTime ();
    cookieTime = 60*60*1000;
    interval = setInterval(function () {
        timeRemaining = (cookieTime-((new Date().getTime())-start))/1000;
        if (timeRemaining <= 0) {
            alert('Your auth cookie has now expired, and you can no longer post this blog.\nPlease copy your content to your clipboard and re-login.');
            document.getElementById('timer').innerText = 'Cookie has expired';
            document.getElementById('submit').style.display = 'none';
            clearInterval(interval);
        } else {
            updateTimer(timeRemaining);
        }
    }, 1000);
}`
	embeddedStatics["theme-gold-black.css"] = `body {
    background-color: black;
}

.site-container {
    background-color: #1e2125;
    color: #fff;
}

a, a:visited {
    color: gold;
}

input[type=text], input[type=password], textarea {
    border: 1px solid gold;
    background-color: #292e33;
    box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
}

input[type=text]:focus, input[type=password]:focus, textarea:focus {
    border-color:#66afe9;
    box-shadow:inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgba(102,175,233,.6)
}

input[type=submit], input[type=button] {
    border: 1px solid gold;
}

input[type=submit]:hover, input[type=button]:hover {
    background-color: rgba(154,204,20,.1);
}

#vis-background-colour {
    background-color: black;
}

#vis-primary-colour {
    background-color: gold;
}

#vis-secondary-colour {
    background-color: gray;
}`
	embeddedStatics["theme-green-black.css"] = `body {
    background-color: black;
}

.site-container {
    background-color: #1e2125;
    color: #fff;
}

a, a:visited {
    color: #9acc14;
}

input[type=text], input[type=password], textarea {
    border: 1px solid #9acc14;
    background-color: #292e33;
    box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
}

input[type=text]:focus, input[type=password]:focus, textarea:focus {
    border-color:#66afe9;
    box-shadow:inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgba(102,175,233,.6)
}

input[type=submit], input[type=button] {
    border: 1px solid #9acc14;
}

input[type=submit]:hover, input[type=button]:hover {
    background-color: rgba(154,204,20,.1);
}

#vis-background-colour {
    background-color: black;
}

#vis-primary-colour {
    background-color: #9acc14;
}

#vis-secondary-colour {
    background-color: gray;
}`
	embeddedStatics["theme-grey-white.css"] = `body {
    background-color: white;
}

.site-container {
    background-color: whitesmoke;
    color: black;
}

a, a:visited {
    color: gray;
}

input[type=text], input[type=password], textarea {
    border: 1px solid black;
    background-color: gray;
    color: white;
    box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
}

input[type=text]:focus, input[type=password]:focus, textarea:focus {
    border-color:#66afe9;
    box-shadow:inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgba(102,175,233,.6)
}

input[type=submit], input[type=button] {
    border: 1px solid gray;
}

input[type=submit]:hover, input[type=button]:hover {
    background-color: rgba(154,204,20,.1);
}

.control-panel {
    color: black;
}

@media only screen and (max-width: 1000px) {
    .control-panel .controls {
        color: black;
    }
}

#vis-background-colour {
    background-color: white;
}

#vis-primary-colour {
    background-color: whitesmoke;
}

#vis-secondary-colour {
    background-color: gray;
}`
	embeddedStatics["theme-purple-black.css"] = `body {
    background-color: black;
}

.site-container {
    background-color: #1e2125;
    color: #fff;
}

a, a:visited {
    color: SlateBlue;
}

input[type=text], input[type=password], textarea {
    border: 1px solid SlateBlue;
    background-color: #292e33;
    box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
}

input[type=text]:focus, input[type=password]:focus, textarea:focus {
    border-color:#66afe9;
    box-shadow:inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgba(102,175,233,.6)
}

input[type=submit], input[type=button] {
    border: 1px solid SlateBlue;
}

input[type=submit]:hover, input[type=button]:hover {
    background-color: rgba(154,204,20,.1);
}

#vis-background-colour {
    background-color: black;
}

#vis-primary-colour {
    background-color: SlateBlue;
}

#vis-secondary-colour {
    background-color: gray;
}`
	embeddedStatics["theme-red-white.css"] = `body {
    background-color: white;
}

.site-container {
    background-color: whitesmoke;
    color: black;
}

a, a:visited {
    color: maroon;
}

input[type=text], input[type=password], textarea {
    border: 1px solid black;
    background-color: maroon;
    color: white;
    box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
}

input[type=text]:focus, input[type=password]:focus, textarea:focus {
    border-color:#66afe9;
    box-shadow:inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgba(102,175,233,.6)
}

input[type=submit], input[type=button] {
    border: 1px solid maroon;
}

input[type=submit]:hover, input[type=button]:hover {
    background-color: rgba(154,204,20,.1);
}

.control-panel {
    color: black;
}

@media only screen and (max-width: 1000px) {
    .control-panel .controls {
        color: black;
    }
}

#vis-background-colour {
    background-color: white;
}

#vis-primary-colour {
    background-color: red;
}

#vis-secondary-colour {
    background-color: maroon;
}`
	embeddedStatics["theme-white-black.css"] = `body {
    background-color: black;
}

.site-container {
    background-color: #1e2125;
    color: #fff;
}

a, a:visited {
    color: white;
}

input[type=text], input[type=password], textarea {
    border: 1px solid white;
    background-color: #292e33;
    box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
}

input[type=text]:focus, input[type=password]:focus, textarea:focus {
    border-color:#66afe9;
    box-shadow:inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgba(102,175,233,.6)
}

input[type=submit], input[type=button] {
    border: 1px solid white;
}

input[type=submit]:hover, input[type=button]:hover {
    background-color: rgba(154,204,20,.1);
}

#vis-background-colour {
    background-color: black;
}

#vis-primary-colour {
    background-color: white;
}

#vis-secondary-colour {
    background-color: #666;
}`
	embeddedStatics["wandering-triangles.js"] = `let wanderingTriangles = {}

// call this to create a basic, default set of settings to modify
wanderingTriangles.baseSettings = function() {
    return {
        fadeAlpha: 0.1,
        framerate: 18,
        triangleSize: 15,
        triangleDensity: 0.5, // how many triangles per triangleSize columns of the canvas
        chanceOfJump: 0.005,
        chanceOfSecondaryColour: 0.25,
        chanceOfFill: 0.5,
        backgroundColour: "black",
        primaryColour: "white",
        secondaryColour: "gray",
    };
}

wanderingTriangles.init = function(canvas, settings) {

    var instance = {
        context: canvas.getContext("2d"),
        settings: settings,
        state: [],
        enabled: true,      // toggle this to false to stop drawning triangles (a 'pause', but with fading)
        intervalHandle: 0     // used to track the internal draw loop
    };

    var interval = 1000 / instance.settings.framerate;
    clearInterval(instance.intervalHandle);
    var self = this;
    instance.intervalHandle = setInterval(function () { 
        self.draw(instance);
    }, interval);

    return instance;
};

wanderingTriangles.draw = function(instance) {
    // an alpha overdraw 'fades out' the triangles
    context = instance.context;
    canvas = context.canvas;
    settings = instance.settings;

    context.fillStyle = settings.backgroundColour;
    context.globalAlpha = settings.fadeAlpha;
    context.fillRect(0, 0, canvas.width, canvas.height);
    context.globalAlpha = 1;

    // only refresh/draw-new triangles if the animation is 'enabled'. this is how pausing works
    if (instance.enabled) {
        var entityCount = (canvas.width / settings.triangleSize) * settings.triangleDensity;
        for (var i = 0; i < entityCount; i++) {
            if (instance.state.length <= i) {
                instance.state.push({
                    x: Math.random() * canvas.width,
                    y: Math.random() * canvas.height,
                    type: Math.floor(Math.random() * 4),
                    colour: settings.primaryColour
                });
            }
            instance.state[i] = this.updateTriangle(instance, instance.state[i])
            this.drawTriangle(instance, instance.state[i])
        }
    }
};

wanderingTriangles.updateTriangle = function(instance, triangle) {

    settings = instance.settings;
    canvas = instance.context.canvas;

    if (triangle.type === 0)
        triangle = this.nextTriangleFromUp(triangle, settings.triangleSize);
    else if (triangle.type === 1)
        triangle = this.nextTriangleFromDown(triangle, settings.triangleSize);
    else if (triangle.type === 2)
        triangle = this.nextTriangleFromLeft(triangle, settings.triangleSize);
    else
        triangle = this.nextTriangleFromRight(triangle, settings.triangleSize);

    let offscreen = 
        triangle.x < -settings.triangleSize ||
        triangle.y < -settings.triangleSize ||
        triangle.x > canvas.width + settings.triangleSize ||
        triangle.y > canvas.height + settings.triangleSize
    if (Math.random() > settings.chanceOfJump && !offscreen) 
        return triangle;
        
    triangle.x = Math.random() * canvas.width;
    triangle.y = Math.random() * canvas.height;
    triangle.type = Math.floor(Math.random() * 4);

    if (Math.random() < settings.chanceOfSecondaryColour)
        triangle.colour = settings.secondaryColour;
    else
        triangle.colour = settings.primaryColour;

    return triangle;
};

wanderingTriangles.drawTriangle = function(instance, triangle) {

    settings = instance.settings;
    context = instance.context;

    context.fillStyle = context.strokeStyle = triangle.colour;
    context.beginPath();
    
    if (triangle.type === 0)
        this.upTrianglePath(context, triangle.x, triangle.y, settings.triangleSize);
    else if (triangle.type === 1)
        this.downTrianglePath(context, triangle.x, triangle.y, settings.triangleSize);
    else if (triangle.type === 2)
        this.leftTrianglePath(context, triangle.x, triangle.y, settings.triangleSize);
    else
        this.rightTrianglePath(context, triangle.x, triangle.y, settings.triangleSize);

    context.closePath();
    if (Math.random() > settings.chanceOfFill)
        context.stroke();
    else
        context.fill();
};

wanderingTriangles.nextTriangleFromUp = function(triangle, triangleSize) {
    var random = Math.random();
    if (random < 0.2)
        triangle.type = 3; // right
    else if (random < 0.4)
        triangle.type = 2; // left
    else {
        triangle.y += triangleSize * 2;
        triangle.type = 1; // down
    }
    return triangle;
};

wanderingTriangles.nextTriangleFromDown = function(triangle, triangleSize) {
    var random = Math.random();
    if (random < 0.2) {
        triangle.y -= triangleSize * 2;
        triangle.type = 0; // up
    }
    else if (random < 0.6)
        triangle.type = 2; // left
    else
        triangle.type = 3; // right
    return triangle;
};
           
wanderingTriangles.nextTriangleFromLeft = function(triangle, triangleSize) {
    var random = Math.random();
    if (random < 0.1) {
        triangle.x += triangleSize;
        triangle.y -= triangleSize;
        triangle.type = 3; // right
    }
    else if (random < 0.4) {
        triangle.x += triangleSize;
        triangle.y += triangleSize;
        triangle.type = 3; // right
    }
    else if (random < 0.7) {
        triangle.x += triangleSize * 2;
        triangle.type = 3; // right
    }
    else
        triangle.type = 0; // up
    return triangle;
};

wanderingTriangles.nextTriangleFromRight = function(triangle, triangleSize) {
    var random = Math.random();
    if (random < 0.1) {
        triangle.x -= triangleSize;
        triangle.y -= triangleSize;
        triangle.type = 2; // left
    }
    else if (random < 0.4) {
        triangle.x -= triangleSize;
        triangle.y += triangleSize;
        triangle.type = 2; // left
    }
    else if (random < 0.7) {
        triangle.x -= triangleSize * 2;
        triangle.type = 2; // left
    }
    else
        triangle.type = 0; // up
    return triangle;
};

wanderingTriangles.upTrianglePath = function (context, x, y, triangleSize) {
    var s = triangleSize;
    context.moveTo(x, y);
    context.lineTo(x - s, y + s);
    context.lineTo(x + s, y + s);
    context.lineTo(x, y);
};

wanderingTriangles.downTrianglePath = function (context, x, y, triangleSize) {
    var s = triangleSize;
    context.moveTo(x, y);
    context.lineTo(x - s, y - s);
    context.lineTo(x + s, y - s);
    context.lineTo(x, y);
};

wanderingTriangles.leftTrianglePath = function (context, x, y, triangleSize) {
    var s = triangleSize;
    context.moveTo(x, y);
    context.lineTo(x + s, y - s);
    context.lineTo(x + s, y + s);
    context.lineTo(x, y);
};

wanderingTriangles.rightTrianglePath = function (context, x, y, triangleSize) {
    var s = triangleSize;
    context.moveTo(x, y);
    context.lineTo(x - s, y - s);
    context.lineTo(x - s, y + s);
    context.lineTo(x, y);
};
`
}
